import { ExerciseLibraryEntry } from '../types/workout';

// Comprehensive exercise database with muscle groups - 240+ exercises
export const defaultExercises: ExerciseLibraryEntry[] = [
  // CHEST EXERCISES (30 exercises)
  {
    name: "BENCH PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INCLINE BENCH PRESS",
    category: "Chest",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts", "Triceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DECLINE BENCH PRESS",
    category: "Chest",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL BENCH PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INCLINE DUMBBELL PRESS",
    category: "Chest",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts", "Triceps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DECLINE DUMBBELL PRESS",
    category: "Chest",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL FLYES",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INCLINE DUMBBELL FLYES",
    category: "Chest",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DECLINE DUMBBELL FLYES",
    category: "Chest",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CHEST DIPS",
    category: "Chest",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PUSH UPS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts", "Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INCLINE PUSH UPS",
    category: "Chest",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DECLINE PUSH UPS",
    category: "Chest",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DIAMOND PUSH UPS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WIDE GRIP PUSH UPS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE CHEST FLYES",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE CROSSOVERS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LOW CABLE CROSSOVERS",
    category: "Chest",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HIGH CABLE CROSSOVERS",
    category: "Chest",
    primaryMuscles: ["Lower Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CHEST PRESS MACHINE",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Front Delts"],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INCLINE CHEST PRESS MACHINE",
    category: "Chest",
    primaryMuscles: ["Upper Chest"],
    secondaryMuscles: ["Front Delts", "Triceps"],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PEC DECK FLYES",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SVEND PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Plates",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LANDMINE PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM DUMBBELL PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Core", "Front Delts"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "FLOOR PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL FLOOR PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL PULLOVERS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Lats", "Triceps"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "RESISTANCE BAND CHEST PRESS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Front Delts", "Triceps"],
    equipment: "Resistance Bands",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "ARCHER PUSH UPS",
    category: "Chest",
    primaryMuscles: ["Chest"],
    secondaryMuscles: ["Triceps", "Core"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },

  // BACK EXERCISES (40 exercises)
  {
    name: "DEADLIFT",
    category: "Back",
    primaryMuscles: ["Lower Back", "Lats", "Traps"],
    secondaryMuscles: ["Glutes", "Hamstrings", "Forearms"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SUMO DEADLIFT",
    category: "Back",
    primaryMuscles: ["Lower Back", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Traps"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "RACK PULLS",
    category: "Back",
    primaryMuscles: ["Traps", "Lower Back"],
    secondaryMuscles: ["Lats", "Rhomboids"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PULL UPS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CHIN UPS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WIDE GRIP PULL UPS",
    category: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Rhomboids", "Biceps"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "NEUTRAL GRIP PULL UPS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WEIGHTED PULL UPS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BARBELL ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids", "Middle Traps"],
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PENDLAY ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "UNDERHAND BARBELL ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM DUMBBELL ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CHEST SUPPORTED DUMBBELL ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "T-BAR ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids", "Middle Traps"],
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "T-Bar",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LANDMINE ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Rear Delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WIDE GRIP CABLE ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Rear Delts"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM CABLE ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LAT PULLDOWNS",
    category: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Rhomboids"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WIDE GRIP LAT PULLDOWNS",
    category: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE GRIP LAT PULLDOWNS",
    category: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "NEUTRAL GRIP LAT PULLDOWNS",
    category: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Rhomboids"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM LAT PULLDOWNS",
    category: "Back",
    primaryMuscles: ["Lats"],
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SHRUGS",
    category: "Back",
    primaryMuscles: ["Traps"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BARBELL SHRUGS",
    category: "Back",
    primaryMuscles: ["Traps"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Barbell",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE SHRUGS",
    category: "Back",
    primaryMuscles: ["Traps"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "FACE PULLS",
    category: "Back",
    primaryMuscles: ["Rear Delts", "Rhomboids"],
    secondaryMuscles: ["Middle Traps"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE FLYES",
    category: "Back",
    primaryMuscles: ["Rear Delts", "Rhomboids"],
    secondaryMuscles: ["Middle Traps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE REVERSE FLYES",
    category: "Back",
    primaryMuscles: ["Rear Delts", "Rhomboids"],
    secondaryMuscles: ["Middle Traps"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INVERTED ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "MACHINE ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HYPEREXTENSIONS",
    category: "Back",
    primaryMuscles: ["Lower Back"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "GOOD MORNINGS",
    category: "Back",
    primaryMuscles: ["Lower Back"],
    secondaryMuscles: ["Hamstrings", "Glutes"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SUPERMAN",
    category: "Back",
    primaryMuscles: ["Lower Back"],
    secondaryMuscles: ["Glutes"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE HYPEREXTENSIONS",
    category: "Back",
    primaryMuscles: ["Lower Back", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "RESISTANCE BAND ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps"],
    equipment: "Resistance Bands",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "KETTLEBELL SWINGS",
    category: "Back",
    primaryMuscles: ["Lower Back", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM KETTLEBELL SWINGS",
    category: "Back",
    primaryMuscles: ["Lower Back", "Glutes"],
    secondaryMuscles: ["Core", "Hamstrings"],
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "MEADOWS ROWS",
    category: "Back",
    primaryMuscles: ["Lats", "Rhomboids"],
    secondaryMuscles: ["Biceps", "Core"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },

  // LEG EXERCISES (50 exercises)
  {
    name: "SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "FRONT SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BACK SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HIGH BAR SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LOW BAR SQUATS",
    category: "Legs",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BOX SQUATS",
    category: "Legs",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PAUSE SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "GOBLET SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core"],
    equipment: "Dumbbell",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SUMO SQUATS",
    category: "Legs",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "JUMP SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Calves"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PISTOL SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Core"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LEG PRESS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE LEG PRESS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Machine",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HACK SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes"],
    equipment: "Machine",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LUNGES",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WALKING LUNGES",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE LUNGES",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LATERAL LUNGES",
    category: "Legs",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CURTSY LUNGES",
    category: "Legs",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL LUNGES",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BARBELL LUNGES",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BULGARIAN SPLIT SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL BULGARIAN SPLIT SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STEP UPS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL STEP UPS",
    category: "Legs",
    primaryMuscles: ["Quadriceps", "Glutes"],
    secondaryMuscles: ["Hamstrings", "Calves"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LEG EXTENSIONS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE LEG EXTENSIONS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LEG CURLS",
    category: "Legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LYING LEG CURLS",
    category: "Legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED LEG CURLS",
    category: "Legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STANDING LEG CURLS",
    category: "Legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "ROMANIAN DEADLIFTS",
    category: "Legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower Back"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL ROMANIAN DEADLIFTS",
    category: "Legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Lower Back"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE LEG ROMANIAN DEADLIFTS",
    category: "Legs",
    primaryMuscles: ["Hamstrings", "Glutes"],
    secondaryMuscles: ["Core"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STIFF LEG DEADLIFTS",
    category: "Legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Lower Back"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL STIFF LEG DEADLIFTS",
    category: "Legs",
    primaryMuscles: ["Hamstrings"],
    secondaryMuscles: ["Glutes", "Lower Back"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CALF RAISES",
    category: "Legs",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STANDING CALF RAISES",
    category: "Legs",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED CALF RAISES",
    category: "Legs",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL CALF RAISES",
    category: "Legs",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE LEG CALF RAISES",
    category: "Legs",
    primaryMuscles: ["Calves"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HIP THRUSTS",
    category: "Legs",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL HIP THRUSTS",
    category: "Legs",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE LEG HIP THRUSTS",
    category: "Legs",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "GLUTE BRIDGES",
    category: "Legs",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE LEG GLUTE BRIDGES",
    category: "Legs",
    primaryMuscles: ["Glutes"],
    secondaryMuscles: ["Hamstrings", "Core"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WALL SITS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: ["Glutes"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SISSY SQUATS",
    category: "Legs",
    primaryMuscles: ["Quadriceps"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "COSSACK SQUATS",
    category: "Legs",
    primaryMuscles: ["Glutes", "Quadriceps"],
    secondaryMuscles: ["Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },

  // SHOULDER EXERCISES (35 exercises)
  {
    name: "OVERHEAD PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "MILITARY PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps", "Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PUSH PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps", "Legs"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED OVERHEAD PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BEHIND THE NECK PRESS",
    category: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL SHOULDER PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED DUMBBELL PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM DUMBBELL PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Core", "Triceps"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "ARNOLD PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LATERAL RAISES",
    category: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE LATERAL RAISES",
    category: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LEANING LATERAL RAISES",
    category: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED LATERAL RAISES",
    category: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "FRONT RAISES",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BARBELL FRONT RAISES",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE FRONT RAISES",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PLATE FRONT RAISES",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: [],
    equipment: "Plates",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REAR DELT FLYES",
    category: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BENT OVER REAR DELT FLYES",
    category: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE REAR DELT FLYES",
    category: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE PEC DECK",
    category: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "UPRIGHT ROWS",
    category: "Shoulders",
    primaryMuscles: ["Side Delts", "Traps"],
    secondaryMuscles: ["Biceps"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL UPRIGHT ROWS",
    category: "Shoulders",
    primaryMuscles: ["Side Delts", "Traps"],
    secondaryMuscles: ["Biceps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE UPRIGHT ROWS",
    category: "Shoulders",
    primaryMuscles: ["Side Delts", "Traps"],
    secondaryMuscles: ["Biceps"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HANDSTAND PUSH UPS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps", "Core"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PIKE PUSH UPS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SHOULDER PRESS MACHINE",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Triceps"],
    equipment: "Machine",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LANDMINE PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: ["Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM LANDMINE PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts"],
    secondaryMuscles: ["Core"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "KETTLEBELL PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Core", "Triceps"],
    equipment: "Kettlebell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BOTTOMS UP KETTLEBELL PRESS",
    category: "Shoulders",
    primaryMuscles: ["Front Delts", "Side Delts"],
    secondaryMuscles: ["Core", "Forearms"],
    equipment: "Kettlebell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BAND PULL APARTS",
    category: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Rhomboids"],
    equipment: "Resistance Bands",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "Y RAISES",
    category: "Shoulders",
    primaryMuscles: ["Side Delts", "Rear Delts"],
    secondaryMuscles: ["Traps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "T RAISES",
    category: "Shoulders",
    primaryMuscles: ["Side Delts"],
    secondaryMuscles: ["Rear Delts"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "W RAISES",
    category: "Shoulders",
    primaryMuscles: ["Rear Delts"],
    secondaryMuscles: ["Rhomboids", "Middle Traps"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },

  // ARM EXERCISES (40 exercises)
  {
    name: "BARBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "EZ BAR CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "EZ Bar",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WIDE GRIP BARBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CLOSE GRIP BARBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "ALTERNATING DUMBBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED DUMBBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "INCLINE DUMBBELL CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HAMMER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps", "Forearms"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CROSS BODY HAMMER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps", "Forearms"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PREACHER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL PREACHER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "EZ BAR PREACHER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "EZ Bar",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CONCENTRATION CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE HAMMER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps", "Forearms"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HIGH CABLE CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "21S CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: ["Forearms"],
    equipment: "Barbell",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SPIDER CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DRAG CURLS",
    category: "Arms",
    primaryMuscles: ["Biceps"],
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "TRICEP DIPS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BENCH DIPS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WEIGHTED DIPS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CLOSE GRIP BENCH PRESS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest", "Front Delts"],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CLOSE GRIP PUSH UPS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "TRICEP PUSHDOWNS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "ROPE TRICEP PUSHDOWNS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE GRIP TRICEP PUSHDOWNS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "OVERHEAD TRICEP EXTENSION",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SEATED OVERHEAD TRICEP EXTENSION",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SINGLE ARM OVERHEAD TRICEP EXTENSION",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Core"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SKULL CRUSHERS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Barbell",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL SKULL CRUSHERS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "EZ BAR SKULL CRUSHERS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "EZ Bar",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "TRICEP KICKBACKS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE TRICEP KICKBACKS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DIAMOND PUSH UPS",
    category: "Arms",
    primaryMuscles: ["Triceps"],
    secondaryMuscles: ["Chest"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WRIST CURLS",
    category: "Arms",
    primaryMuscles: ["Forearms"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE WRIST CURLS",
    category: "Arms",
    primaryMuscles: ["Forearms"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "FARMER'S WALKS",
    category: "Arms",
    primaryMuscles: ["Forearms"],
    secondaryMuscles: ["Traps", "Core"],
    equipment: "Dumbbells",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },

  // CORE EXERCISES (45 exercises)
  {
    name: "PLANKS",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SIDE PLANKS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Core"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PLANK UP DOWNS",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "PLANK TO PUSH UP",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Chest", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE PLANK",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Glutes", "Hamstrings"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CRUNCHES",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "REVERSE CRUNCHES",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BICYCLE CRUNCHES",
    category: "Core",
    primaryMuscles: ["Abs", "Obliques"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CROSS CRUNCHES",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WEIGHTED CRUNCHES",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: [],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "RUSSIAN TWISTS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WEIGHTED RUSSIAN TWISTS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Abs"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "MEDICINE BALL RUSSIAN TWISTS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Abs"],
    equipment: "Medicine Ball",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "LEG RAISES",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HANGING LEG RAISES",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: ["Forearms"],
    equipment: "Pull-up Bar",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HANGING KNEE RAISES",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: ["Forearms"],
    equipment: "Pull-up Bar",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CAPTAIN'S CHAIR LEG RAISES",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: [],
    equipment: "Machine",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "MOUNTAIN CLIMBERS",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Legs"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BURPEES",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Chest", "Legs", "Shoulders"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DEAD BUG",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BIRD DOG",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Glutes", "Lower Back"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HOLLOW BODY HOLD",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "V UPS",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SIT UPS",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WEIGHTED SIT UPS",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DECLINE SIT UPS",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "FLUTTER KICKS",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "SCISSOR KICKS",
    category: "Core",
    primaryMuscles: ["Lower Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HEEL TOUCHES",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WOOD CHOPS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Core"],
    equipment: "Cable",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DUMBBELL WOOD CHOPS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Core"],
    equipment: "Dumbbells",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CABLE CRUNCHES",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: [],
    equipment: "Cable",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "AB WHEEL ROLLOUTS",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders"],
    equipment: "Ab Wheel",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "KNEE TO ELBOW",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Abs"],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STANDING OBLIQUE CRUNCHES",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: [],
    equipment: "Bodyweight",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "WINDSHIELD WIPERS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Lower Abs"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "HANGING WINDSHIELD WIPERS",
    category: "Core",
    primaryMuscles: ["Obliques"],
    secondaryMuscles: ["Lower Abs", "Forearms"],
    equipment: "Pull-up Bar",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "DRAGON FLAGS",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Lower Back"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "L SITS",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Triceps"],
    equipment: "Bodyweight",
    difficulty: "Advanced",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "TUCK UPS",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "JACKKNIFE SIT UPS",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: ["Hip Flexors"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STABILITY BALL CRUNCHES",
    category: "Core",
    primaryMuscles: ["Abs"],
    secondaryMuscles: [],
    equipment: "Stability Ball",
    difficulty: "Beginner",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "STABILITY BALL PIKE",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders"],
    equipment: "Stability Ball",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "BEAR CRAWL",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Legs"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  },
  {
    name: "CRAB WALK",
    category: "Core",
    primaryMuscles: ["Core"],
    secondaryMuscles: ["Shoulders", "Glutes"],
    equipment: "Bodyweight",
    difficulty: "Intermediate",
    lastUsed: 0,
    timesUsed: 0,
    isCustom: false
  }
];

// Helper function to get exercises by category
export const getExercisesByCategory = (category: string): ExerciseLibraryEntry[] => {
  return defaultExercises.filter(exercise => exercise.category === category);
};

// Helper function to get exercises by muscle group
export const getExercisesByMuscle = (muscle: string): ExerciseLibraryEntry[] => {
  return defaultExercises.filter(exercise => 
    exercise.primaryMuscles.includes(muscle) || exercise.secondaryMuscles.includes(muscle)
  );
};

// Get all unique muscle groups
export const getAllMuscleGroups = (): string[] => {
  const muscles = new Set<string>();
  defaultExercises.forEach(exercise => {
    exercise.primaryMuscles.forEach(muscle => muscles.add(muscle));
    exercise.secondaryMuscles.forEach(muscle => muscles.add(muscle));
  });
  return Array.from(muscles).sort();
};

// Get all categories
export const getAllCategories = (): string[] => {
  const categories = new Set<string>();
  defaultExercises.forEach(exercise => categories.add(exercise.category));
  return Array.from(categories).sort();
};